version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - run:
          command: pip install --user -r requirements-dev.txt
      - python/save-cache
      - run:
          command: python -m pybaseballdatana.data.tools.update --data-source Lahman --make-dirs
          name: Update Lahman
      - run:
          command: python -m pybaseballdatana.data.tools.update --data-source BaseballReference --make-dirs
          name: Update Baseball Reference
      - run:
          command: python -m pybaseballdatana.data.tools.update --data-source Fangraphs --make-dirs --min-year 2019 --max-year 2019 --num-threads 2
          name: Update Fangraphs
      - run:
          command: python -m pybaseballdatana.data.tools.update --min-year 1982 --max-year 1982 --data-source retrosheet
          name: Update Retrosheet Events
      - run:
          command: make lint
          name: Lint
      - run:
          command: make test
          name: Test
      - run:
          command: make test-markov
          name: Test Markov CLI

workflows:
  main:
    jobs:
      - build-and-test
